In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import pickle

df=pd.read_csv(r"/Users/vaibhav/Desktop/AI_project/spam_mail_prediction/email.csv")
print(df.shape)
print(df.head())
print(df['Category'].value_counts())

(5573, 2)
  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
Category
ham               4825
spam               747
{"mode":"full"       1
Name: count, dtype: int64


In [3]:
labelln=LabelEncoder()
label=labelln.fit_transform(df['Category'])
df['target']=label
x=df.Message
y=df.target
print(x)
print(y)


0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
5572                                      isActive:false}
Name: Message, Length: 5573, dtype: str
0       0
1       0
2       1
3       0
4       0
       ..
5568    0
5569    0
5570    0
5571    0
5572    2
Name: target, Length: 5573, dtype: int64


In [4]:
x_train,x_text,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=3)
print(x.shape)
print(x_train.shape)
print(x_text.shape)

(5573,)
(4458,)
(1115,)


In [5]:
feature_extraction=TfidfVectorizer(min_df=1,stop_words='english')
x_train_feature=feature_extraction.fit_transform(x_train)
x_test_feature=feature_extraction.transform(x_text)
print(x_train)
print(x_train_feature.toarray())

2315    Also that chat was awesome but don't make it r...
2041          You always make things bigger than they are
3079               Okay but i thought you were the expert
3423    Freemsg: 1-month unlimited free calls! Activat...
1698    Hai priya are you right. What doctor said pa. ...
                              ...                        
789     5 Free Top Polyphonic Tones call 087018728737,...
968     What do u want when i come back?.a beautiful n...
1667    Guess who spent all last night phasing in and ...
3321    Eh sorry leh... I din c ur msg. Not sad alread...
1688    Free Top ringtone -sub to weekly ringtone-get ...
Name: Message, Length: 4458, dtype: str
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [6]:
model=MultinomialNB()
model.fit(x_train_feature,y_train)
#prediction on training data
prediction_on_training_data=model.predict(x_train_feature)
accuracy_score_on_trian=accuracy_score(y_train,prediction_on_training_data)
print(f"Accuracy on traindata: {accuracy_score_on_trian}")
#prediction on testing data
prediction_on_testing_data=model.predict(x_test_feature)
accuracy_score_on_test=accuracy_score(y_test,prediction_on_testing_data)
print(f"Accuracy on testdata: {accuracy_score_on_test}")

Accuracy on traindata: 0.9822790489008524
Accuracy on testdata: 0.9739910313901345


In [7]:
#save files
with open("model.pkl",'wb') as f:
    pickle.dump(model,f)

with open("vectorer.pkl","wb") as f:
    pickle.dump(feature_extraction,f)

print("saved succesfully")

saved succesfully
